#!/usr/bin/python
# -*- coding: utf-8 -*-

from bs4 import BeautifulSoup
import urllib2
import sys


if (len(sys.argv) == 1):
    # TODO: Use argparse
    print("Usage: mango [OPTION]... [NAME] [OPTION]...")
    print("Try 'mango --help' for more information.")

else:

    if (sys.argv[1] == "-h") or (sys.argv[1] == "--h") or (sys.argv[1] == "-help") or (sys.argv[1] == "--help"):
        print("Usage: mango [--avaliable][--download]... <NAME> [--all][--chapter]...<CHAPTER>\n")
        print("The most commonly used mango command are:")
        print("\tavaliable\tVerify that the manga is available")
        print("\tdownload\tDownload a Manga informed")
        print("\tchapter\t\tDownload a chapter informed")
        print("\tall\t\tDownload all chapters avaliable")

    elif (sys.argv[1] == "-a") or (sys.argv[1] == "--a") or (sys.argv[1] == "-avaliable") or (
                sys.argv[1] == "--avaliable"):
        url = "http://centraldemangas.net/mangas/list/*"

        headers = {'User-Agent': 'Mozilla/5.0'}
        html = urllib2.urlopen(urllib2.Request(url, None, headers)).read()
        soup = BeautifulSoup(html)

        pages = soup.find('ul', {'class': 'pagination pagination-sm'}).find_all('li')
        mangas = []
        for n_page in xrange(len(pages)):
            page = BeautifulSoup(urllib2.urlopen(urllib2.Request(url + "/" + str(n_page + 1), None, headers)).read())
            rows = page.find_all('tr')
            for row in rows:
                cols = row.find_all('td')
                name = ""
                rating = 0
                for col in cols:  # Get ready, ugly rack this comming!
                    stars = col.find_all('span', attrs={'class': 'glyphicon glyphicon-star'})
                    if (stars != []):
                        rating = len(stars)
                    else:
                        colValue = col.find('a')
                        if not colValue is None:
                            name = colValue.getText()
                if name:
                    mangas.append([name, rating])
        for i in mangas:
            for x in range(0,5):
                if i[1] >= x+1:
                    print u"\u2605",
                else:
                    print u"\u2606",
            print "\t" + i[0]

    elif (sys.argv[1] == "-d") or (sys.argv[1] == "--d") or (sys.argv[1] == "-download") or (
                sys.argv[1] == "--download"):
        if len(sys.argv) > 2:
            manga = sys.argv[2].lower().replace(" ", "-")
            url = "http://centraldemangas.net/mangas/info/" + manga
            header = {'User-Agent': 'Mozilla/5.0'}
            req = urllib2.Request(url, headers=header)
            page = urllib2.urlopen(req)
            text = page.read().decode("utf-8")

            soup = BeautifulSoup(text)
            chapters = []
            for chapter in soup.find_all('center'):
                for value in chapter.find_all('a', attrs={'class':'col-xs-1 col-sm-1 col-md-1 col-lg-1'}):
                    value = str(value['href'])
                    chapters.append("http://centraldemangas.net"+value)
            chapters.sort()

            if (sys.argv[3] == "-c") or (sys.argv[3] == "--c") or (sys.argv[3] == "-chapter") or (
                        sys.argv[3] == "--chapter"):

                url = chapters[int(sys.argv[4]) - 1]
                req = urllib2.Request(url, headers=header)
                page = urllib2.urlopen(req)
                text = page.read()
                soup = BeautifulSoup(text)

                number = []
                for pags in soup.find_all(attrs={'id':'manga_pages'}):
                    for pag in pags.find_all('option'):
                        number.append( url + "#" + str(int( pag['value'])+1))

                images = []
                for num in number:
                    req = urllib2.Request(num, headers=header)
                    page = urllib2.urlopen(req)
                    text = page.read()
                    soup = BeautifulSoup(text)
#Infelizmente este site usa os url's das paginas dentro de um array Javascript.
#Vou pensar como solucionar este problema.
    else:
        print("Download!")


